Updated Mock guidance with extra steps to hit api
UKHomeOffice/lev-api-spec pull request #35
Opened 2021-03-16 15:38 UTC by aarongill1

![Screenshot from 2021-03-15 17-26-12](https://user-images.githubusercontent.com/22613578/111336495-3396a500-866d-11eb-8f8d-f4720b8f0176.png)
![Screenshot from 2021-03-15 17-26-18](https://user-images.githubusercontent.com/22613578/111336502-35f8ff00-866d-11eb-91bf-25bd494ad9d6.png)

2021-03-16 15:58 UTC, daniel-ac-martin commented on assets/sections/life-event-verification-lev-api/templates/guides/Mock.md
>  docker run -p 80:8080 --env 'MOCK=true' quay.io/ukhomeofficedigital/lev-api:latest
I think we could give the container a name here if we wanted.

2021-03-16 16:00 UTC, daniel-ac-martin commented on assets/sections/life-event-verification-lev-api/templates/guides/Mock.md
> +```
Why not just direct them to https://github.com/UKHomeOffice/lev-api/tree/master/mock ?

2021-03-17 10:14 UTC, RobinKnipe commented on assets/sections/life-event-verification-lev-api/templates/guides/Mock.md
>  docker run -p 80:8080 --env 'MOCK=true' quay.io/ukhomeofficedigital/lev-api:latest
Good idea. Then it would be easier to refer to in later steps, e.g.
```shell
docker run --name lev-api-mock -p 80:8080 --env 'MOCK=true' quay.io/ukhomeofficedigital/lev-api:latest
```
...then you can do things like:
```shell
docker exec -it lev-api-mock bash
```
...and avoid a `docker ps` step.

2021-03-17 10:18 UTC, RobinKnipe commented on assets/sections/life-event-verification-lev-api/templates/guides/Mock.md
> +```
I think you should do both. The link that Daniel provides is the set of files that will be included in the `latest` version, but it's still potentially useful to know where they live in the mock, not least (as we discussed) you could easily replace the `*.json` files with your own to allow you to test against test data specific to a client's requirements.

2021-07-28 16:01 UTC, RobinKnipe requested changes
Just a couple of small changes to consider, but otherwise LGTM

2021-07-28 16:01 UTC, RobinKnipe commented on assets/sections/life-event-verification-lev-api/templates/guides/Authentication.md
> +     -H "Authorization: Bearer YOUR_TOKEN" \
...also worth doing something similar on line `56` above too.

2021-07-28 16:17 UTC, aarongill1 commented on assets/sections/life-event-verification-lev-api/templates/guides/Authentication.md
> +     -H "Authorization: Bearer YOUR_TOKEN" \
Done

2021-07-28 16:17 UTC, merged

2021-07-28 17:21 UTC, RobinKnipe reviewed
Another minor change and I think you're done!

2021-07-28 17:21 UTC, RobinKnipe commented on assets/sections/life-event-verification-lev-api/templates/guides/Authentication.md
> +     -d "client_id=$YOUR_CLIENT_ID&client_secret=$YOUR_CLIENT_SECRET&username=$SOME_USER&password=$SOME_USERS_PASSWORD&grant_type=password" \
Maybe just:
```shell
  -d "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&username=$USERNAME&password=$PASSWORD&grant_type=password" \
```

2021-07-29 10:41 UTC, daniel-ac-martin commented on assets/sections/life-event-verification-lev-api/templates/guides/Authentication.md
> +     -d "client_id=$YOUR_CLIENT_ID&client_secret=$YOUR_CLIENT_SECRET&username=$SOME_USER&password=$SOME_USERS_PASSWORD&grant_type=password" \
Is it useful to parameterise this?

2021-07-29 10:42 UTC, daniel-ac-martin commented on assets/sections/life-event-verification-lev-api/templates/guides/Authentication.md
> +     -H "Authorization: Bearer YOUR_TOKEN" \
If we make it a shell var, don't we need a line to set the shell var?
In which case, does it help?